# Пути к файлам
input_excel_file: "Обработка заказов из ORM.xlsx"
output_excel_file: "Подбор_заготовок_алгоритм.xlsx"

# Имена листов в Excel файле
sheet_names:
  sap: "Выгрузка САП"
  model: "Модель"
  order: "Заказы"

# Штрафные коэффициенты для оптимизатора
penalties:
  slack: 100000.0    # Штраф за недобор заказа (переменная s)
  blanks: 1.0        # Штраф за использование каждой уникальной заготовки (переменная z)
  sets: 10.0         # Штраф за каждый используемый набор характеристик (переменная w)
  rkm: 1000.0        # Штраф, связанный с РКМ (переменная x)
